### ISSUE TITLE
'Sequential' object has no attribute 'augment_images'

### ISSUE THREAD

**Issue by jolly12138** [okankop/vidaug#2]
hi，thank you for your code. When I use your example an error occurred ‘Sequential' object has no attribute 'augment_images’. Can you tell me how to slove it?

from vidaug import augmentors as va

sometimes = lambda aug: va.Sometimes(0.5, aug) # Used to apply augmentor with 50% probability
seq = va.Sequential([
    va.RandomCrop(size=(240, 180)), # randomly crop video with a size of (240 x 180)
    va.RandomRotate(degrees=10), # randomly rotates the video with a degree randomly choosen from [-10, 10]  
    sometimes(va.HorizontalFlip()) # horizontally flip the video with 50% probability
])

for batch_idx in range(1000):
    # 'video' should be either a list of images from type of numpy array or PIL images
    video = load_batch(batch_idx)
    video_aug = seq.augment_images(video)
    train_on_video(video)

Thank you!

**Comment by Hiteshi16** [comment]
Same doubt .. Could you solve it?

**Comment by MounirB** [comment]
**seq(video)** will apply data augmentation on the video clip sent as a parameter. **No need to use the non-existing function augment_images**

**Comment by ahmetgunduz** [comment]
it is fixed now. No need for augment_images()
