### ISSUE TITLE
How can I load batch images   through load_batch() function

### ISSUE THREAD

**Issue by adeebakausar** [okankop/vidaug#6]
for batch_idx in range(1000):
    # 'video' should be either a list of images from type of numpy array or PIL images
    video = load_batch(batch_idx)
    video_aug = seq(video)
    train_on_video(video)

**Comment by ahmetgunduz** [comment]
That is just a **pseudo code.** If you are using PyTorch for example,  that would be dataloader item for example.

**Comment by adeebakausar** [comment]
as a example, can you share exact code ?

**Comment by ahmetgunduz** [comment]
Sure, soon I will add one for machine learning training.

**Comment by wajiharas** [comment]
1 also

**Comment by wajiharas** [comment]
I also tried a lot of time  to run this repo, but  because of the psedue code i cant understand how i read  the video so it is better to  give example with python code to run this repo rather than psedue code .

**Comment by ahmetgunduz** [comment]
@wajiharas , could you please check examples folder where I give an example of horizontalfipping?

**Comment by okankop** [comment]
I believe the issue is resolved! You can reopen the issue if necessary!
