### ISSUE TITLE
Sequence exists with only message "Killed"

### ISSUE THREAD

**Issue by tsaxena** [okankop/vidaug#8]
Hi,
  I am applying the  pepper or salt augmenters  but the process keeps getting killed and I am not sure why. Only message is "Killed". I tried to look for where this might be coming from but could not identify the source.

**Comment by ahmetgunduz** [comment]
Can you please share your code where it get killed? Are you sure about the input format is proper?

**Comment by tsaxena** [comment]
I have a ".mov" file and I extract frames using ffmpeg. Before calling the augmentor, I read all the files using glob and PIL and then call the augmentor. 

```for image_path in frames:
                image = Image.open(image_path)
                frame_images.append(image.convert("RGB"))

        return frame_images```

**Comment by tsaxena** [comment]
The super useless exception occurs for high resolution videos and is coming from PIL, not the vidaug source code.
